export const LOAD_CHILD_LIST = "LOAD_CHILD_LIST";
export const ADD_CHILD = "ADD_CHILD";
export const LOAD_CHILD = "LOAD_CHILD";
export const DELETE_CHILD = "DELETE_CHILD";

export const SET_SELECTED_NAV_ITEM_P = "SET_SELECTED_NAV_ITEM_P";
export const SET_SELECTED_NAV_ITEM_S = "SET_SELECTED_NAV_ITEM_S";

export const SET_RACE_TIME = "SET_RACE_TIME";

export const LOAD_PARENT = "LOAD_PARENT";

export const SHOW_BARSIDE = "SHOW_BARSIDE";
export const HIDE_BARSIDE = "HIDE_BARSIDE";

export const SET_CURRENT_STEP = "SET_CURRENT_STEP";

export const LOAD_PREPARING_RACE_PAGE = "LOAD_PREPARING_RACE_PAGE";
export const RESTART_PREPARING_RACE_PAGE = "RESTART_PREPARING_RACE_PAGE";